---
# tasks file for zap

- name: Zap | Group
  group:
    name: "{{zap_group}}"
  tags: zap_install

- name: Zap | User
  user:
    name: "{{zap_user}}"
    home: "{{zap_user_home}}"
    shell: "{{zap_user_shell}}"
    group: "{{zap_group}}"
    createhome: true

- name: Check Install
  stat:
    path: "{{zap_jar_home}}/ZAP_{{zap_version}}/zap-{{zap_version}}.jar"
  register: jar_installed

- block:
  - name: Download Tar
    unarchive:
      src: "https://github.com/zaproxy/zaproxy/releases/download/{{zap_version}}/ZAP_{{zap_version}}_Linux.tar.gz"
      dest: "{{zap_jar_home}}/"
      copy: false
  when: jar_installed is defined and not jar_installed.stat.exists

- block:
  - name: Install Init Script
    template:
      dest: /etc/init.d/zap
      mode: 0755
      owner: root
      src: zap.init.sh.j2
    notify: restart zap
  when: ansible_service_mgr != 'systemd'

- block:
  - name: Make Config Path
    file:
      name: /etc/zap
      owner: root
      group: root
      mode: 0700
      state: directory

  - name: Install Service
    template:
      dest: /etc/systemd/system/zap.service
      src: zap.service.j2
      owner: root
      group: root
      mode: 0600
    register: zap_service_change
    notify: restart zap

  - name: Reload
    systemd:
      daemon_reload: yes
    when: zap_service_change is changed

  when: ansible_service_mgr == 'systemd'

- name: Enable Service
  service:
    name: zap
    enabled: true
    state: started
