---
# handlers file for zap

- name: start zap
  service:
    name: zap
    state: started
  listen: "start application"

- name: restart zap
  service:
    name: zap
    state: restarted
  listen: "restart application"
